os:
  - linux

language: php

php:
  - '7.1'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --no-suggest
  - cp .env.travis .env
  - php artisan key:generate
  - yes | php artisan migrate
  - php artisan passport:keys
  - nvm install 11.15.0
  - npm install npm@latest -g
  - npm install

script:
  - vendor/bin/phpunit --coverage-text
  - npm run production
