os:
  - linux

language: php

php:
  - '7.1'

before_script:
  - composer self-update
  - composer install --no-interaction
  - phpenv rehash
  - nvm install 11.15.0
  - npm install 6.10.3 -g
  - npm install

script:
  - vendor/bin/phpunit --coverage-text
  - npm run production
